### ISSUE TITLE
Rename the files with different logic.

### ISSUE THREAD

**Issue by AneriMehta** [AneriMehta/DivisibilityTestPrograms#72]
The files with different logic need to be renamed like FirstTestFor2.py, SecondTestFor2.py. The duplicates need not be touched as there is an issue for that.

**Comment by kishan3** [comment]
Not clear which files are files with different logic?

**Comment by AneriMehta** [comment]
Programs that are testing the divisibility rule of same number but have different logic. Like one uses bitwise operator and other sums up the digits of the the given number to test.
