### ISSUE TITLE
Remove the duplicate folders.

### ISSUE THREAD

**Issue by AneriMehta** [AneriMehta/DivisibilityTestPrograms#73]
There are two duplicate folders one for javascript and one for python. You need to remove one of them and copy the files if any that are not present in the second one to the second folder.

**Comment by kishan3** [comment]
Solved in #81

**Comment by kishan3** [comment]
Hey, Why this was opened again?

**Comment by AneriMehta** [comment]
The duplicates were created again so I had to open the issue again.
